stages:
  - build
  - test
  - deploy

# Build Stage
build:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - .next
      - node_modules
      - package-lock.json

# Test Stage node jov

test:
  stage: test
  image: node:16
  script:
    - npm install
    - npm test

# Deploy to Vercel
deploy-vercel:
  stage: deploy
  image: node:16
  script:
    - npm install -g vercel
    - vercel --token $VERCEL_TOKEN --prod
  only:
    - main  # Deploy only on the main branch
